// auto-generated
// Code generated by 'fynematic'. DO NOT EDIT.

package icon

import "fyne.io/fyne/v2"

var CircleCheckOutlinedIconThemed = NewThemedResource(CircleCheckOutlinedIconDarkRes, CircleCheckOutlinedIconLightRes)

var CircleCheckOutlinedIconDarkRes = &fyne.StaticResource{
	StaticName:    "circlecheck_outlined_dark.svg",
	StaticContent: []byte("<!--category: Shapestags: [accept, yes, tick, done]version: \"1.0\"unicode: \"ea67\"--><svg  xmlns=\"http://www.w3.org/2000/svg\"  width=\"24\"  height=\"24\"  viewBox=\"0 0 24 24\"  fill=\"none\"  stroke=\"#ffffff\"  stroke-width=\"2\"  stroke-linecap=\"round\"  stroke-linejoin=\"round\">  <path d=\"M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0\" />  <path d=\"M9 12l2 2l4 -4\" /></svg>"),
}

var CircleCheckOutlinedIconLightRes = &fyne.StaticResource{
	StaticName:    "circlecheck_outlined_light.svg",
	StaticContent: []byte("<!--category: Shapestags: [accept, yes, tick, done]version: \"1.0\"unicode: \"ea67\"--><svg  xmlns=\"http://www.w3.org/2000/svg\"  width=\"24\"  height=\"24\"  viewBox=\"0 0 24 24\"  fill=\"none\"  stroke=\"#000000\"  stroke-width=\"2\"  stroke-linecap=\"round\"  stroke-linejoin=\"round\">  <path d=\"M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0\" />  <path d=\"M9 12l2 2l4 -4\" /></svg>"),
}
