// auto-generated
// Code generated by 'fynematic'. DO NOT EDIT.

package icon

import "fyne.io/fyne/v2"

var DownloadOutlinedIconThemed = NewThemedResource(DownloadOutlinedIconDarkRes, DownloadOutlinedIconLightRes)

var DownloadOutlinedIconDarkRes = &fyne.StaticResource{
	StaticName:    "download_outlined_dark.svg",
	StaticContent: []byte("<!--category: Arrowstags: [save, arrow]version: \"1.0\"unicode: \"ea96\"--><svg  xmlns=\"http://www.w3.org/2000/svg\"  width=\"24\"  height=\"24\"  viewBox=\"0 0 24 24\"  fill=\"none\"  stroke=\"#ffffff\"  stroke-width=\"2\"  stroke-linecap=\"round\"  stroke-linejoin=\"round\">  <path d=\"M4 17v2a2 2 0 0 0 2 2h12a2 2 0 0 0 2 -2v-2\" />  <path d=\"M7 11l5 5l5 -5\" />  <path d=\"M12 4l0 12\" /></svg>"),
}

var DownloadOutlinedIconLightRes = &fyne.StaticResource{
	StaticName:    "download_outlined_light.svg",
	StaticContent: []byte("<!--category: Arrowstags: [save, arrow]version: \"1.0\"unicode: \"ea96\"--><svg  xmlns=\"http://www.w3.org/2000/svg\"  width=\"24\"  height=\"24\"  viewBox=\"0 0 24 24\"  fill=\"none\"  stroke=\"#000000\"  stroke-width=\"2\"  stroke-linecap=\"round\"  stroke-linejoin=\"round\">  <path d=\"M4 17v2a2 2 0 0 0 2 2h12a2 2 0 0 0 2 -2v-2\" />  <path d=\"M7 11l5 5l5 -5\" />  <path d=\"M12 4l0 12\" /></svg>"),
}
