// auto-generated
// Code generated by 'fynematic'. DO NOT EDIT.

package icon

import "fyne.io/fyne/v2"

var LockOpenOutlinedIconThemed = NewThemedResource(LockOpenOutlinedIconDarkRes, LockOpenOutlinedIconLightRes)

var LockOpenOutlinedIconDarkRes = &fyne.StaticResource{
	StaticName:    "lock_open_outlined_dark.svg",
	StaticContent: []byte("<!--category: Systemtags: [security, password, secure, unprotected]version: \"1.0\"unicode: \"eae1\"--><svg  xmlns=\"http://www.w3.org/2000/svg\"  width=\"24\"  height=\"24\"  viewBox=\"0 0 24 24\"  fill=\"none\"  stroke=\"#ffffff\"  stroke-width=\"2\"  stroke-linecap=\"round\"  stroke-linejoin=\"round\">  <path d=\"M5 11m0 2a2 2 0 0 1 2 -2h10a2 2 0 0 1 2 2v6a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2z\" />  <path d=\"M12 16m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0\" />  <path d=\"M8 11v-5a4 4 0 0 1 8 0\" /></svg>"),
}

var LockOpenOutlinedIconLightRes = &fyne.StaticResource{
	StaticName:    "lock_open_outlined_light.svg",
	StaticContent: []byte("<!--category: Systemtags: [security, password, secure, unprotected]version: \"1.0\"unicode: \"eae1\"--><svg  xmlns=\"http://www.w3.org/2000/svg\"  width=\"24\"  height=\"24\"  viewBox=\"0 0 24 24\"  fill=\"none\"  stroke=\"#000000\"  stroke-width=\"2\"  stroke-linecap=\"round\"  stroke-linejoin=\"round\">  <path d=\"M5 11m0 2a2 2 0 0 1 2 -2h10a2 2 0 0 1 2 2v6a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2z\" />  <path d=\"M12 16m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0\" />  <path d=\"M8 11v-5a4 4 0 0 1 8 0\" /></svg>"),
}
