// auto-generated
// Code generated by 'fynematic'. DO NOT EDIT.

package icon

import "fyne.io/fyne/v2"

var PasswordOutlinedIconThemed = NewThemedResource(PasswordOutlinedIconDarkRes, PasswordOutlinedIconLightRes)

var PasswordOutlinedIconDarkRes = &fyne.StaticResource{
	StaticName:    "password_outlined_dark.svg",
	StaticContent: []byte("<!--tags: [lock, secure, privacy, locked, login]unicode: \"f4ca\"version: \"1.98\"category: System--><svg  xmlns=\"http://www.w3.org/2000/svg\"  width=\"24\"  height=\"24\"  viewBox=\"0 0 24 24\"  fill=\"none\"  stroke=\"#ffffff\"  stroke-width=\"2\"  stroke-linecap=\"round\"  stroke-linejoin=\"round\">  <path d=\"M12 10v4\" />  <path d=\"M10 13l4 -2\" />  <path d=\"M10 11l4 2\" />  <path d=\"M5 10v4\" />  <path d=\"M3 13l4 -2\" />  <path d=\"M3 11l4 2\" />  <path d=\"M19 10v4\" />  <path d=\"M17 13l4 -2\" />  <path d=\"M17 11l4 2\" /></svg>"),
}

var PasswordOutlinedIconLightRes = &fyne.StaticResource{
	StaticName:    "password_outlined_light.svg",
	StaticContent: []byte("<!--tags: [lock, secure, privacy, locked, login]unicode: \"f4ca\"version: \"1.98\"category: System--><svg  xmlns=\"http://www.w3.org/2000/svg\"  width=\"24\"  height=\"24\"  viewBox=\"0 0 24 24\"  fill=\"none\"  stroke=\"#000000\"  stroke-width=\"2\"  stroke-linecap=\"round\"  stroke-linejoin=\"round\">  <path d=\"M12 10v4\" />  <path d=\"M10 13l4 -2\" />  <path d=\"M10 11l4 2\" />  <path d=\"M5 10v4\" />  <path d=\"M3 13l4 -2\" />  <path d=\"M3 11l4 2\" />  <path d=\"M19 10v4\" />  <path d=\"M17 13l4 -2\" />  <path d=\"M17 11l4 2\" /></svg>"),
}
