// auto-generated
// Code generated by 'fynematic'. DO NOT EDIT.

package icon

import "fyne.io/fyne/v2"

var UploadOutlinedIconThemed = NewThemedResource(UploadOutlinedIconDarkRes, UploadOutlinedIconLightRes)

var UploadOutlinedIconDarkRes = &fyne.StaticResource{
	StaticName:    "upload_outlined_dark.svg",
	StaticContent: []byte("<svg fill=\"#ffffff\" xmlns=\"http://www.w3.org/2000/svg\" height=\"24\" viewBox=\"0 0 24 24\" width=\"24\"><path d=\"M0 0h24v24H0V0z\" fill=\"none\"/><path d=\"M9 16h6v-6h4l-7-7-7 7h4v6zm3-10.17L14.17 8H13v6h-2V8H9.83L12 5.83zM5 18h14v2H5z\"/></svg>"),
}

var UploadOutlinedIconLightRes = &fyne.StaticResource{
	StaticName:    "upload_outlined_light.svg",
	StaticContent: []byte("<svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24\" viewBox=\"0 0 24 24\" width=\"24\"><path d=\"M0 0h24v24H0V0z\" fill=\"none\"/><path d=\"M9 16h6v-6h4l-7-7-7 7h4v6zm3-10.17L14.17 8H13v6h-2V8H9.83L12 5.83zM5 18h14v2H5z\"/></svg>"),
}
