// auto-generated
// Code generated by 'fynematic'. DO NOT EDIT.

package icon

import "fyne.io/fyne/v2"

var WorldWWWOutlinedIconThemed = NewThemedResource(WorldWWWOutlinedIconDarkRes, WorldWWWOutlinedIconLightRes)

var WorldWWWOutlinedIconDarkRes = &fyne.StaticResource{
	StaticName:    "worldwWW_outlined_dark.svg",
	StaticContent: []byte("<!--tags: [internet, online, web, website, browser]category: Mapunicode: \"f38f\"version: \"1.91\"--><svg  xmlns=\"http://www.w3.org/2000/svg\"  width=\"24\"  height=\"24\"  viewBox=\"0 0 24 24\"  fill=\"none\"  stroke=\"#ffffff\"  stroke-width=\"2\"  stroke-linecap=\"round\"  stroke-linejoin=\"round\">  <path d=\"M19.5 7a9 9 0 0 0 -7.5 -4a8.991 8.991 0 0 0 -7.484 4\" />  <path d=\"M11.5 3a16.989 16.989 0 0 0 -1.826 4\" />  <path d=\"M12.5 3a16.989 16.989 0 0 1 1.828 4\" />  <path d=\"M19.5 17a9 9 0 0 1 -7.5 4a8.991 8.991 0 0 1 -7.484 -4\" />  <path d=\"M11.5 21a16.989 16.989 0 0 1 -1.826 -4\" />  <path d=\"M12.5 21a16.989 16.989 0 0 0 1.828 -4\" />  <path d=\"M2 10l1 4l1.5 -4l1.5 4l1 -4\" />  <path d=\"M17 10l1 4l1.5 -4l1.5 4l1 -4\" />  <path d=\"M9.5 10l1 4l1.5 -4l1.5 4l1 -4\" /></svg>"),
}

var WorldWWWOutlinedIconLightRes = &fyne.StaticResource{
	StaticName:    "worldwWW_outlined_light.svg",
	StaticContent: []byte("<!--tags: [internet, online, web, website, browser]category: Mapunicode: \"f38f\"version: \"1.91\"--><svg  xmlns=\"http://www.w3.org/2000/svg\"  width=\"24\"  height=\"24\"  viewBox=\"0 0 24 24\"  fill=\"none\"  stroke=\"#000000\"  stroke-width=\"2\"  stroke-linecap=\"round\"  stroke-linejoin=\"round\">  <path d=\"M19.5 7a9 9 0 0 0 -7.5 -4a8.991 8.991 0 0 0 -7.484 4\" />  <path d=\"M11.5 3a16.989 16.989 0 0 0 -1.826 4\" />  <path d=\"M12.5 3a16.989 16.989 0 0 1 1.828 4\" />  <path d=\"M19.5 17a9 9 0 0 1 -7.5 4a8.991 8.991 0 0 1 -7.484 -4\" />  <path d=\"M11.5 21a16.989 16.989 0 0 1 -1.826 -4\" />  <path d=\"M12.5 21a16.989 16.989 0 0 0 1.828 -4\" />  <path d=\"M2 10l1 4l1.5 -4l1.5 4l1 -4\" />  <path d=\"M17 10l1 4l1.5 -4l1.5 4l1 -4\" />  <path d=\"M9.5 10l1 4l1.5 -4l1.5 4l1 -4\" /></svg>"),
}
